// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMDFKCD5qYnm8o49Um-uh0Z3Ouv-bfvA',
    appId: '1:180485618206:android:a6c81a627c79836f2c4c0f',
    messagingSenderId: '180485618206',
    projectId: 'whatsapp-2a679',
    storageBucket: 'whatsapp-2a679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrDq67st5yazxMYSYLqMYlxRwj-7K-3g',
    appId: '1:180485618206:ios:de462d30a3a870cc2c4c0f',
    messagingSenderId: '180485618206',
    projectId: 'whatsapp-2a679',
    storageBucket: 'whatsapp-2a679.appspot.com',
    androidClientId: '180485618206-dpd74302km0ht8kls4hiupd5lderc24u.apps.googleusercontent.com',
    iosClientId: '180485618206-cqvea5juujpe8lqavvg7us89dbafkfve.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
